# Generated by Django 4.2.15 on 2024-08-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherlog',
            name='humidity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
