# Generated by Django 4.2.15 on 2024-08-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherlog_humidity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherlog',
            old_name='date_time',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='weatherlog',
            name='response',
            field=models.JSONField(null=True),
        ),
    ]
